// -----------------------------------------------------------------------------
// This header is generated by the Vellum ABI compiler.
// Do not edit.
// -----------------------------------------------------------------------------

#pragma once

#include <cstdint>
#include <cstddef>
#include <utility>
#include <vellum.hpp>

{% include "c++/_structs.hpp" %}

{% include "c++/_functions.hpp" %}
