"""
This module is generated by the Vellum ABI compiler.
Do not edit.
"""

import ctypes as ct
import vellum

{%- for s in items.abstract_structs %}
class {{ s.name }}(ct.Structure):
    pass

{%- endfor %}

{%- for s in items.structs %}
class {{ s.name }}(ct.Structure):
    _fields_ = [
    {%- for field in s.fields %}
        ('{{ field.name }}', {{ field.ty|ty }}),
    {%- endfor %}
    ]

{%- endfor %}

def load(*args):
    lib = ct.CDLL(*args)

    {%- for f in items.functions %}
    lib.{{ f.name }}.argtypes = [
        {%- for arg in f.args %}
        {{ arg.1|ty }},
        {%- endfor %}
    ]
    lib.{{ f.name }}.restype = {{ f.returns|retty }}
    {%- endfor %}

    return lib
