// -----------------------------------------------------------------------------
// This header is generated by the Vellum ABI compiler.
// Do not edit.
// -----------------------------------------------------------------------------

#pragma once

#include "{{ header_name }}"

{% import "c/_macros.h" as m %}

#ifdef __cplusplus
extern "C" {
#endif

{% for f in items.functions %}
{{ f.returns|retty }} vellum_implement_{{ f.name }}(
{%- for arg in f.args %}
    {{ arg.1|ty }} {{ arg.0 }}{% call m::comma() %}
{%- endfor %}
);

{% endfor %}

#ifdef __cplusplus
}
#endif
