// -----------------------------------------------------------------------------
// This source file is generated by the Vellum ABI compiler.
// Do not edit.
// -----------------------------------------------------------------------------

#undef VELLUM_ABI
#if defined(VELLUM_STATIC)
#  define VELLUM_ABI
#elif defined(_WIN32) || defined(__CYGWIN__)
#  define VELLUM_ABI __declspec(dllexport)
#else
#  define VELLUM_ABI __attribute__((visibility("default")))
#endif
#include "{{ header_name }}"
#include "{{ implementation_header_name }}"

{% import "c/_macros.h" as m %}

{% for f in items.functions %}
VELLUM_ABI {{ f.returns|retty }} {{ f.name }}(
{%- for arg in f.args %}
    {{ arg.1|ty }} {{ arg.0 }}{% call m::comma() %}
{%- endfor %}
) {
{%- if f.returns.is_some() %}
    return vellum_implement_{{ f.name }}(
{%- else %}
    vellum_implement_{{ f.name }}(
{%- endif %}
{%- for arg in f.args %}
        {{ arg.0 }}{% call m::comma() %}
{%- endfor %}
    );
}

{% endfor %}
