name: Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  multi-language:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: pip install pytest

      - name: Run multi-language example tests
        run: pytest examples/multi-language/tests -v
